esphome:
  name: modbus-sniffer
  platform: ESP32
  board: esp32dev

# Configuration WiFi
wifi:
  ssid: "VotreSSID"
  password: "VotreMotDePasse"

# API et OTA
api:
logger:
  level: DEBUG
ota:
  - platform: esphome

# Configuration UART pour le bus Modbus
uart:
  - id: uart_0
    tx_pin: GPIO01
    rx_pin: GPIO03
    baud_rate: 9600
    # data_bits: 8
    # stop_bits: 1
    # parity: NONE

# Composant externe
external_components:
  - source: "github://SeByDocKy/myESPhome/"
    components: [modbus_sniffer]
    refresh: 0s

# Hub Modbus Sniffer
modbus_sniffer:
  - id: my_sniffer
    uart_id: uart_0
    address: 1  # Optionnel: filtre sur l'adresse esclave

# Sensors Modbus
sensor:
  # Exemple 1: Lecture d'un registre 16 bits non signé (WORD)
  - platform: modbus_sniffer
    modbus_sniffer_id: my_sniffer
    name: "Power"
    id: power
    address: 0x0100
    value_type: U_WORD
    register_type: holding
    unit_of_measurement: "W"
    accuracy_decimals: 1
    device_class: power
    state_class: measurement
    icon: mdi:power

  # Exemple 2: Lecture d'un registre 16 bits signé
  - platform: modbus_sniffer
    modbus_sniffer_id: my_sniffer
    name: "Temperature"
    id: temperature
    address: 0x0200
    value_type: S_WORD
    register_type: input
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    device_class: temperature
    state_class: measurement
    filters:
      - multiply: 0.1  # Si la valeur est en dixièmes de degré

  # Exemple 3: Lecture d'un registre 32 bits (2 registres consécutifs)
  - platform: modbus_sniffer
    modbus_sniffer_id: my_sniffer
    name: "Energy Total"
    id: energy
    address: 0x0300
    value_type: U_DWORD  # 32-bit unsigned
    register_type: holding
    unit_of_measurement: "kWh"
    accuracy_decimals: 2
    device_class: energy
    state_class: total_increasing

  # Exemple 4: Lecture d'un float 32 bits
  - platform: modbus_sniffer
    modbus_sniffer_id: my_sniffer
    name: "Voltage"
    id: voltage
    address: 0x0400
    value_type: FP32  # Float 32-bit
    register_type: holding
    unit_of_measurement: "V"
    accuracy_decimals: 2
    device_class: voltage
    state_class: measurement

  # Exemple 5: Float 32 bits avec registres inversés
  - platform: modbus_sniffer
    modbus_sniffer_id: my_sniffer
    name: "Current"
    id: current
    address: 0x0500
    value_type: FP32_R  # Float 32-bit reversed (low word first)
    register_type: holding
    unit_of_measurement: "A"
    accuracy_decimals: 3
    device_class: current
    state_class: measurement
