/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_ALARMDATA_PB_H_INCLUDED
#define PB_ALARMDATA_PB_H_INCLUDED
#include "pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _WInfoMO {
    int64_t pv_sn; /* Inverter serial number this warning belongs to */
    int32_t WCode; /* Warning code: wcode1 = WCode & 0xFF, wcode2 = (WCode >> 8) & 0xFFFFFF */
    int32_t WNum; /* Occurrence number */
    int32_t WTime1; /* Start timestamp (warning is active if WTime1 != 0 && WTime2 == 0) */
    int32_t WTime2; /* Stop timestamp (0 while still active) */
    int32_t WData1; /* Auxiliary data (meaning not documented) */
    int32_t WData2; /* Auxiliary data (meaning not documented) */
} WInfoMO;

/* DTU -> client: the actual warning list, in reply to WInfoResDTO below. */
typedef struct _WInfoReqDTO {
    char dtu_sn[20]; /* DTU serial number */
    int32_t time; /* Timestamp of the request */
    int32_t package_count;
    int32_t package_idx;
    int32_t warn_device;
    pb_size_t mWInfo_count;
    WInfoMO mWInfo[30];
} WInfoReqDTO;

/* client -> DTU: "give me the current warning list" request. */
typedef struct _WInfoResDTO {
    char time_ymd_hms[24];
    int32_t error_code;
    int32_t offset;
    int32_t time;
} WInfoResDTO;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define WInfoMO_init_default                     {0, 0, 0, 0, 0, 0, 0}
#define WInfoReqDTO_init_default                 {"", 0, 0, 0, 0, 0, {WInfoMO_init_default, WInfoMO_init_default, WInfoMO_init_default, WInfoMO_init_default, WInfoMO_init_default, WInfoMO_init_default, WInfoMO_init_default, WInfoMO_init_default, WInfoMO_init_default, WInfoMO_init_default, WInfoMO_init_default, WInfoMO_init_default, WInfoMO_init_default, WInfoMO_init_default, WInfoMO_init_default, WInfoMO_init_default, WInfoMO_init_default, WInfoMO_init_default, WInfoMO_init_default, WInfoMO_init_default, WInfoMO_init_default, WInfoMO_init_default, WInfoMO_init_default, WInfoMO_init_default, WInfoMO_init_default, WInfoMO_init_default, WInfoMO_init_default, WInfoMO_init_default, WInfoMO_init_default, WInfoMO_init_default}}
#define WInfoResDTO_init_default                 {"", 0, 0, 0}
#define WInfoMO_init_zero                        {0, 0, 0, 0, 0, 0, 0}
#define WInfoReqDTO_init_zero                    {"", 0, 0, 0, 0, 0, {WInfoMO_init_zero, WInfoMO_init_zero, WInfoMO_init_zero, WInfoMO_init_zero, WInfoMO_init_zero, WInfoMO_init_zero, WInfoMO_init_zero, WInfoMO_init_zero, WInfoMO_init_zero, WInfoMO_init_zero, WInfoMO_init_zero, WInfoMO_init_zero, WInfoMO_init_zero, WInfoMO_init_zero, WInfoMO_init_zero, WInfoMO_init_zero, WInfoMO_init_zero, WInfoMO_init_zero, WInfoMO_init_zero, WInfoMO_init_zero, WInfoMO_init_zero, WInfoMO_init_zero, WInfoMO_init_zero, WInfoMO_init_zero, WInfoMO_init_zero, WInfoMO_init_zero, WInfoMO_init_zero, WInfoMO_init_zero, WInfoMO_init_zero, WInfoMO_init_zero}}
#define WInfoResDTO_init_zero                    {"", 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define WInfoMO_pv_sn_tag                        1
#define WInfoMO_WCode_tag                        2
#define WInfoMO_WNum_tag                         3
#define WInfoMO_WTime1_tag                       4
#define WInfoMO_WTime2_tag                       5
#define WInfoMO_WData1_tag                       6
#define WInfoMO_WData2_tag                       7
#define WInfoReqDTO_dtu_sn_tag                   1
#define WInfoReqDTO_time_tag                     2
#define WInfoReqDTO_package_count_tag            3
#define WInfoReqDTO_package_idx_tag              4
#define WInfoReqDTO_warn_device_tag              5
#define WInfoReqDTO_mWInfo_tag                   6
#define WInfoResDTO_time_ymd_hms_tag             1
#define WInfoResDTO_error_code_tag               2
#define WInfoResDTO_offset_tag                   3
#define WInfoResDTO_time_tag                     4

/* Struct field encoding specification for nanopb */
#define WInfoMO_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT64,    pv_sn,             1) \
X(a, STATIC,   SINGULAR, INT32,    WCode,             2) \
X(a, STATIC,   SINGULAR, INT32,    WNum,              3) \
X(a, STATIC,   SINGULAR, INT32,    WTime1,            4) \
X(a, STATIC,   SINGULAR, INT32,    WTime2,            5) \
X(a, STATIC,   SINGULAR, INT32,    WData1,            6) \
X(a, STATIC,   SINGULAR, INT32,    WData2,            7)
#define WInfoMO_CALLBACK NULL
#define WInfoMO_DEFAULT NULL

#define WInfoReqDTO_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   dtu_sn,            1) \
X(a, STATIC,   SINGULAR, INT32,    time,              2) \
X(a, STATIC,   SINGULAR, INT32,    package_count,     3) \
X(a, STATIC,   SINGULAR, INT32,    package_idx,       4) \
X(a, STATIC,   SINGULAR, INT32,    warn_device,       5) \
X(a, STATIC,   REPEATED, MESSAGE,  mWInfo,            6)
#define WInfoReqDTO_CALLBACK NULL
#define WInfoReqDTO_DEFAULT NULL
#define WInfoReqDTO_mWInfo_MSGTYPE WInfoMO

#define WInfoResDTO_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   time_ymd_hms,      1) \
X(a, STATIC,   SINGULAR, INT32,    error_code,        2) \
X(a, STATIC,   SINGULAR, INT32,    offset,            3) \
X(a, STATIC,   SINGULAR, INT32,    time,              4)
#define WInfoResDTO_CALLBACK NULL
#define WInfoResDTO_DEFAULT NULL

extern const pb_msgdesc_t WInfoMO_msg;
extern const pb_msgdesc_t WInfoReqDTO_msg;
extern const pb_msgdesc_t WInfoResDTO_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define WInfoMO_fields &WInfoMO_msg
#define WInfoReqDTO_fields &WInfoReqDTO_msg
#define WInfoResDTO_fields &WInfoResDTO_msg

/* Maximum encoded size of messages (where known) */
#define ALARMDATA_PB_H_MAX_SIZE                  WInfoReqDTO_size
#define WInfoMO_size                             77
#define WInfoReqDTO_size                         2435
#define WInfoResDTO_size                         58

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
