/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_APPHEARTBEATPB_PB_H_INCLUDED
#define PB_APPHEARTBEATPB_PB_H_INCLUDED
#include "pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _HBReqDTO {
    int32_t offset; /* Offset value */
    int32_t time; /* Timestamp of the request */
    int32_t csq; /* Carrier Signal Quality (CSQ) */
    char dtu_serial_number[16]; /* DTU serial number */
    char device_serial_number[16]; /* Device serial number */
} HBReqDTO;

typedef PB_BYTES_ARRAY_T(24) HBResDTO_time_ymd_hms_t;
typedef struct _HBResDTO {
    int32_t offset; /* Offset value */
    int32_t time; /* Timestamp of the response */
    HBResDTO_time_ymd_hms_t time_ymd_hms; /* Timestamp in the format YMD_HMS */
} HBResDTO;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define HBReqDTO_init_default                    {0, 0, 0, "", ""}
#define HBResDTO_init_default                    {0, 0, {0, {0}}}
#define HBReqDTO_init_zero                       {0, 0, 0, "", ""}
#define HBResDTO_init_zero                       {0, 0, {0, {0}}}

/* Field tags (for use in manual encoding/decoding) */
#define HBReqDTO_offset_tag                      1
#define HBReqDTO_time_tag                        2
#define HBReqDTO_csq_tag                         3
#define HBReqDTO_dtu_serial_number_tag           4
#define HBReqDTO_device_serial_number_tag        5
#define HBResDTO_offset_tag                      1
#define HBResDTO_time_tag                        2
#define HBResDTO_time_ymd_hms_tag                3

/* Struct field encoding specification for nanopb */
#define HBReqDTO_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    offset,            1) \
X(a, STATIC,   SINGULAR, INT32,    time,              2) \
X(a, STATIC,   SINGULAR, INT32,    csq,               3) \
X(a, STATIC,   SINGULAR, STRING,   dtu_serial_number,   4) \
X(a, STATIC,   SINGULAR, STRING,   device_serial_number,   5)
#define HBReqDTO_CALLBACK NULL
#define HBReqDTO_DEFAULT NULL

#define HBResDTO_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    offset,            1) \
X(a, STATIC,   SINGULAR, INT32,    time,              2) \
X(a, STATIC,   SINGULAR, BYTES,    time_ymd_hms,      3)
#define HBResDTO_CALLBACK NULL
#define HBResDTO_DEFAULT NULL

extern const pb_msgdesc_t HBReqDTO_msg;
extern const pb_msgdesc_t HBResDTO_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define HBReqDTO_fields &HBReqDTO_msg
#define HBResDTO_fields &HBResDTO_msg

/* Maximum encoded size of messages (where known) */
#define APPHEARTBEATPB_PB_H_MAX_SIZE             HBReqDTO_size
#define HBReqDTO_size                            67
#define HBResDTO_size                            48

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
