/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_COMMANDPB_PB_H_INCLUDED
#define PB_COMMANDPB_PB_H_INCLUDED
#include "pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _CommandResDTO {
    int32_t time; /* Timestamp of the response */
    int32_t action; /* Action code indicating the type of command */
    int32_t dev_kind; /* Device kind information */
    int32_t package_nub; /* Total number of packages expected */
    int32_t package_now; /* Current package number */
    int64_t tid; /* Transaction ID? */
    char data[32]; /* Additional data payload */
    pb_size_t es_to_sn_count;
    char es_to_sn[1][8]; /* List of ES serial numbers */
    pb_size_t mi_to_sn_count;
    int64_t mi_to_sn[1]; /* List of MI serial numbers */
    int32_t system_total_a; /* System total for category A */
    int32_t system_total_b; /* System total for category B */
    int32_t system_total_c; /* System total for category C */
    pb_size_t mi_sn_item_a_count;
    int64_t mi_sn_item_a[1]; /* List of MI serial numbers for category A */
    pb_size_t mi_sn_item_b_count;
    int64_t mi_sn_item_b[1]; /* List of MI serial numbers for category B */
    pb_size_t mi_sn_item_c_count;
    int64_t mi_sn_item_c[1]; /* List of MI serial numbers for category C */
} CommandResDTO;

typedef struct _CommandReqDTO {
    char dtu_sn[16]; /* Data Terminal Unit (DTU) serial number */
    int32_t time; /* Timestamp of the request */
    int32_t action; /* Action code indicating the type of command */
    int32_t package_now; /* Current package number */
    int32_t err_code; /* Error code (if any) */
    int64_t tid; /* Transaction ID */
} CommandReqDTO;

typedef struct _ESOperatingStatusMO {
    char es_sn[16]; /* ES serial number */
    int32_t progress_rate; /* Progress rate of the operation */
} ESOperatingStatusMO;

typedef struct _MIOperatingStatusMO {
    int64_t mi_sn; /* MI serial number */
    int32_t progress_rate; /* Progress rate of the operation */
} MIOperatingStatusMO;

typedef struct _MIErrorStatusMO {
    int64_t mi_sn; /* MI serial number */
    int64_t error_code; /* Error code associated with the MI */
} MIErrorStatusMO;

typedef struct _ESSucStatusMO {
    char es_sn[16]; /* ES serial number */
} ESSucStatusMO;

typedef struct _ESErrorStatusMO {
    char es_sn[16]; /* ES serial number */
    int64_t error_code; /* Error code associated with the ES */
} ESErrorStatusMO;

typedef struct _CommandStatusReqDTO {
    char dtu_sn[16]; /* Data Terminal Unit (DTU) serial number */
    int32_t time; /* Timestamp of the request */
    int32_t action; /* Action code indicating the type of command */
    int32_t package_nub; /* Total number of packages expected */
    int32_t package_now; /* Current package number */
    int64_t tid; /* Transaction ID */
    pb_size_t es_sns_sucs_count;
    char es_sns_sucs[1][8]; /* List of ES serial numbers with successful execution */
    pb_size_t mi_sns_sucs_count;
    int64_t mi_sns_sucs[1]; /* List of MI serial numbers with successful execution */
    pb_size_t es_sns_failds_count;
    char es_sns_failds[1][8]; /* List of ES serial numbers with failed execution */
    pb_size_t mi_sns_failds_count;
    int64_t mi_sns_failds[1]; /* List of MI serial numbers with failed execution */
    pb_size_t es_mOperatingStatus_count;
    ESOperatingStatusMO es_mOperatingStatus[1]; /* List of ES operating statuses */
    pb_size_t mi_mOperatingStatus_count;
    MIOperatingStatusMO mi_mOperatingStatus[1]; /* List of MI operating statuses */
    pb_size_t mi_mErrorStatus_count;
    MIErrorStatusMO mi_mErrorStatus[1]; /* List of MI error statuses */
    pb_size_t es_mSucStatus_count;
    ESSucStatusMO es_mSucStatus[1]; /* List of successful ES statuses */
    pb_size_t es_mErrorStatus_count;
    ESErrorStatusMO es_mErrorStatus[1]; /* List of error ES statuses */
} CommandStatusReqDTO;

typedef struct _CommandStatusResDTO {
    int32_t time; /* Timestamp of the response */
    int32_t action; /* Action code indicating the type of command */
    int32_t package_now; /* Current package number */
    int64_t tid; /* Transaction ID */
    int32_t err_code; /* Error code (if any) */
} CommandStatusResDTO;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define CommandResDTO_init_default               {0, 0, 0, 0, 0, 0, "", 0, {""}, 0, {0}, 0, 0, 0, 0, {0}, 0, {0}, 0, {0}}
#define CommandReqDTO_init_default               {"", 0, 0, 0, 0, 0}
#define ESOperatingStatusMO_init_default         {"", 0}
#define MIOperatingStatusMO_init_default         {0, 0}
#define MIErrorStatusMO_init_default             {0, 0}
#define ESSucStatusMO_init_default               {""}
#define ESErrorStatusMO_init_default             {"", 0}
#define CommandStatusReqDTO_init_default         {"", 0, 0, 0, 0, 0, 0, {""}, 0, {0}, 0, {""}, 0, {0}, 0, {ESOperatingStatusMO_init_default}, 0, {MIOperatingStatusMO_init_default}, 0, {MIErrorStatusMO_init_default}, 0, {ESSucStatusMO_init_default}, 0, {ESErrorStatusMO_init_default}}
#define CommandStatusResDTO_init_default         {0, 0, 0, 0, 0}
#define CommandResDTO_init_zero                  {0, 0, 0, 0, 0, 0, "", 0, {""}, 0, {0}, 0, 0, 0, 0, {0}, 0, {0}, 0, {0}}
#define CommandReqDTO_init_zero                  {"", 0, 0, 0, 0, 0}
#define ESOperatingStatusMO_init_zero            {"", 0}
#define MIOperatingStatusMO_init_zero            {0, 0}
#define MIErrorStatusMO_init_zero                {0, 0}
#define ESSucStatusMO_init_zero                  {""}
#define ESErrorStatusMO_init_zero                {"", 0}
#define CommandStatusReqDTO_init_zero            {"", 0, 0, 0, 0, 0, 0, {""}, 0, {0}, 0, {""}, 0, {0}, 0, {ESOperatingStatusMO_init_zero}, 0, {MIOperatingStatusMO_init_zero}, 0, {MIErrorStatusMO_init_zero}, 0, {ESSucStatusMO_init_zero}, 0, {ESErrorStatusMO_init_zero}}
#define CommandStatusResDTO_init_zero            {0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define CommandResDTO_time_tag                   1
#define CommandResDTO_action_tag                 2
#define CommandResDTO_dev_kind_tag               3
#define CommandResDTO_package_nub_tag            4
#define CommandResDTO_package_now_tag            5
#define CommandResDTO_tid_tag                    6
#define CommandResDTO_data_tag                   7
#define CommandResDTO_es_to_sn_tag               8
#define CommandResDTO_mi_to_sn_tag               9
#define CommandResDTO_system_total_a_tag         10
#define CommandResDTO_system_total_b_tag         11
#define CommandResDTO_system_total_c_tag         12
#define CommandResDTO_mi_sn_item_a_tag           13
#define CommandResDTO_mi_sn_item_b_tag           14
#define CommandResDTO_mi_sn_item_c_tag           15
#define CommandReqDTO_dtu_sn_tag                 1
#define CommandReqDTO_time_tag                   2
#define CommandReqDTO_action_tag                 3
#define CommandReqDTO_package_now_tag            4
#define CommandReqDTO_err_code_tag               5
#define CommandReqDTO_tid_tag                    6
#define ESOperatingStatusMO_es_sn_tag            1
#define ESOperatingStatusMO_progress_rate_tag    2
#define MIOperatingStatusMO_mi_sn_tag            1
#define MIOperatingStatusMO_progress_rate_tag    2
#define MIErrorStatusMO_mi_sn_tag                1
#define MIErrorStatusMO_error_code_tag           2
#define ESSucStatusMO_es_sn_tag                  1
#define ESErrorStatusMO_es_sn_tag                1
#define ESErrorStatusMO_error_code_tag           2
#define CommandStatusReqDTO_dtu_sn_tag           1
#define CommandStatusReqDTO_time_tag             2
#define CommandStatusReqDTO_action_tag           3
#define CommandStatusReqDTO_package_nub_tag      4
#define CommandStatusReqDTO_package_now_tag      5
#define CommandStatusReqDTO_tid_tag              6
#define CommandStatusReqDTO_es_sns_sucs_tag      7
#define CommandStatusReqDTO_mi_sns_sucs_tag      8
#define CommandStatusReqDTO_es_sns_failds_tag    9
#define CommandStatusReqDTO_mi_sns_failds_tag    10
#define CommandStatusReqDTO_es_mOperatingStatus_tag 11
#define CommandStatusReqDTO_mi_mOperatingStatus_tag 12
#define CommandStatusReqDTO_mi_mErrorStatus_tag  13
#define CommandStatusReqDTO_es_mSucStatus_tag    14
#define CommandStatusReqDTO_es_mErrorStatus_tag  15
#define CommandStatusResDTO_time_tag             1
#define CommandStatusResDTO_action_tag           2
#define CommandStatusResDTO_package_now_tag      3
#define CommandStatusResDTO_tid_tag              4
#define CommandStatusResDTO_err_code_tag         5

/* Struct field encoding specification for nanopb */
#define CommandResDTO_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    time,              1) \
X(a, STATIC,   SINGULAR, INT32,    action,            2) \
X(a, STATIC,   SINGULAR, INT32,    dev_kind,          3) \
X(a, STATIC,   SINGULAR, INT32,    package_nub,       4) \
X(a, STATIC,   SINGULAR, INT32,    package_now,       5) \
X(a, STATIC,   SINGULAR, INT64,    tid,               6) \
X(a, STATIC,   SINGULAR, STRING,   data,              7) \
X(a, STATIC,   REPEATED, STRING,   es_to_sn,          8) \
X(a, STATIC,   REPEATED, INT64,    mi_to_sn,          9) \
X(a, STATIC,   SINGULAR, INT32,    system_total_a,   10) \
X(a, STATIC,   SINGULAR, INT32,    system_total_b,   11) \
X(a, STATIC,   SINGULAR, INT32,    system_total_c,   12) \
X(a, STATIC,   REPEATED, INT64,    mi_sn_item_a,     13) \
X(a, STATIC,   REPEATED, INT64,    mi_sn_item_b,     14) \
X(a, STATIC,   REPEATED, INT64,    mi_sn_item_c,     15)
#define CommandResDTO_CALLBACK NULL
#define CommandResDTO_DEFAULT NULL

#define CommandReqDTO_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   dtu_sn,            1) \
X(a, STATIC,   SINGULAR, INT32,    time,              2) \
X(a, STATIC,   SINGULAR, INT32,    action,            3) \
X(a, STATIC,   SINGULAR, INT32,    package_now,       4) \
X(a, STATIC,   SINGULAR, INT32,    err_code,          5) \
X(a, STATIC,   SINGULAR, INT64,    tid,               6)
#define CommandReqDTO_CALLBACK NULL
#define CommandReqDTO_DEFAULT NULL

#define ESOperatingStatusMO_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   es_sn,             1) \
X(a, STATIC,   SINGULAR, INT32,    progress_rate,     2)
#define ESOperatingStatusMO_CALLBACK NULL
#define ESOperatingStatusMO_DEFAULT NULL

#define MIOperatingStatusMO_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT64,    mi_sn,             1) \
X(a, STATIC,   SINGULAR, INT32,    progress_rate,     2)
#define MIOperatingStatusMO_CALLBACK NULL
#define MIOperatingStatusMO_DEFAULT NULL

#define MIErrorStatusMO_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT64,    mi_sn,             1) \
X(a, STATIC,   SINGULAR, INT64,    error_code,        2)
#define MIErrorStatusMO_CALLBACK NULL
#define MIErrorStatusMO_DEFAULT NULL

#define ESSucStatusMO_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   es_sn,             1)
#define ESSucStatusMO_CALLBACK NULL
#define ESSucStatusMO_DEFAULT NULL

#define ESErrorStatusMO_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   es_sn,             1) \
X(a, STATIC,   SINGULAR, INT64,    error_code,        2)
#define ESErrorStatusMO_CALLBACK NULL
#define ESErrorStatusMO_DEFAULT NULL

#define CommandStatusReqDTO_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   dtu_sn,            1) \
X(a, STATIC,   SINGULAR, INT32,    time,              2) \
X(a, STATIC,   SINGULAR, INT32,    action,            3) \
X(a, STATIC,   SINGULAR, INT32,    package_nub,       4) \
X(a, STATIC,   SINGULAR, INT32,    package_now,       5) \
X(a, STATIC,   SINGULAR, INT64,    tid,               6) \
X(a, STATIC,   REPEATED, STRING,   es_sns_sucs,       7) \
X(a, STATIC,   REPEATED, INT64,    mi_sns_sucs,       8) \
X(a, STATIC,   REPEATED, STRING,   es_sns_failds,     9) \
X(a, STATIC,   REPEATED, INT64,    mi_sns_failds,    10) \
X(a, STATIC,   REPEATED, MESSAGE,  es_mOperatingStatus,  11) \
X(a, STATIC,   REPEATED, MESSAGE,  mi_mOperatingStatus,  12) \
X(a, STATIC,   REPEATED, MESSAGE,  mi_mErrorStatus,  13) \
X(a, STATIC,   REPEATED, MESSAGE,  es_mSucStatus,    14) \
X(a, STATIC,   REPEATED, MESSAGE,  es_mErrorStatus,  15)
#define CommandStatusReqDTO_CALLBACK NULL
#define CommandStatusReqDTO_DEFAULT NULL
#define CommandStatusReqDTO_es_mOperatingStatus_MSGTYPE ESOperatingStatusMO
#define CommandStatusReqDTO_mi_mOperatingStatus_MSGTYPE MIOperatingStatusMO
#define CommandStatusReqDTO_mi_mErrorStatus_MSGTYPE MIErrorStatusMO
#define CommandStatusReqDTO_es_mSucStatus_MSGTYPE ESSucStatusMO
#define CommandStatusReqDTO_es_mErrorStatus_MSGTYPE ESErrorStatusMO

#define CommandStatusResDTO_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    time,              1) \
X(a, STATIC,   SINGULAR, INT32,    action,            2) \
X(a, STATIC,   SINGULAR, INT32,    package_now,       3) \
X(a, STATIC,   SINGULAR, INT64,    tid,               4) \
X(a, STATIC,   SINGULAR, INT32,    err_code,          5)
#define CommandStatusResDTO_CALLBACK NULL
#define CommandStatusResDTO_DEFAULT NULL

extern const pb_msgdesc_t CommandResDTO_msg;
extern const pb_msgdesc_t CommandReqDTO_msg;
extern const pb_msgdesc_t ESOperatingStatusMO_msg;
extern const pb_msgdesc_t MIOperatingStatusMO_msg;
extern const pb_msgdesc_t MIErrorStatusMO_msg;
extern const pb_msgdesc_t ESSucStatusMO_msg;
extern const pb_msgdesc_t ESErrorStatusMO_msg;
extern const pb_msgdesc_t CommandStatusReqDTO_msg;
extern const pb_msgdesc_t CommandStatusResDTO_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define CommandResDTO_fields &CommandResDTO_msg
#define CommandReqDTO_fields &CommandReqDTO_msg
#define ESOperatingStatusMO_fields &ESOperatingStatusMO_msg
#define MIOperatingStatusMO_fields &MIOperatingStatusMO_msg
#define MIErrorStatusMO_fields &MIErrorStatusMO_msg
#define ESSucStatusMO_fields &ESSucStatusMO_msg
#define ESErrorStatusMO_fields &ESErrorStatusMO_msg
#define CommandStatusReqDTO_fields &CommandStatusReqDTO_msg
#define CommandStatusResDTO_fields &CommandStatusResDTO_msg

/* Maximum encoded size of messages (where known) */
#define COMMANDPB_PB_H_MAX_SIZE                  CommandStatusReqDTO_size
#define CommandReqDTO_size                       72
#define CommandResDTO_size                       190
#define CommandStatusReqDTO_size                 248
#define CommandStatusResDTO_size                 55
#define ESErrorStatusMO_size                     28
#define ESOperatingStatusMO_size                 28
#define ESSucStatusMO_size                       17
#define MIErrorStatusMO_size                     22
#define MIOperatingStatusMO_size                 22

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
