/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_REALDATA_PB_H_INCLUDED
#define PB_REALDATA_PB_H_INCLUDED
#include "pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _MeterDataMO {
    int32_t device_kind; /* Device kind identifier */
    int64_t meter_sn; /* Meter serial number */
    int32_t meter_total_power; /* Total power by the meter (Watts) */
    int32_t meter_phase_A_power; /* Power in phase A (Watts) */
    int32_t meter_phase_B_power; /* Power in phase B (Watts) */
    int32_t meter_phase_C_power; /* Power in phase C (Watts) */
    int32_t meter_factor; /* Meter factor */
    int32_t meter_total_energy; /* Total energy produced (Watt-hours) */
    int32_t meter_phase_A_energy; /* Energy produced in phase A (Watt-hours) */
    int32_t meter_phase_B_energy; /* Energy produced in phase B (Watt-hours) */
    int32_t meter_phase_C_energy; /* Energy produced in phase C (Watt-hours) */
    int32_t meter_total_consumed; /* Total energy consumed (Watt-hours) */
    int32_t meter_phase_A_consumed; /* Energy consumed in phase A (Watt-hours) */
    int32_t meter_phase_B_consumed; /* Energy consumed in phase B (Watt-hours) */
    int32_t meter_phase_C_consumed; /* Energy consumed in phase C (Watt-hours) */
    int32_t meter_fault; /* Meter fault code */
} MeterDataMO;

typedef struct _RpDataMO {
    int64_t rp_sn; /* RP serial number */
    int32_t rp_signal; /* RP signal strength */
    int32_t rp_channel; /* RP channel number */
    int32_t rp_link_nub; /* RP link number */
    int32_t rp_link_status; /* RP link status */
} RpDataMO;

typedef struct _PvDataMO {
    int64_t pv_sn; /* PV serial number */
    int32_t pv_port; /* PV port number */
    int32_t pv_vol; /* PV voltage (Volts) */
    int32_t pv_cur; /* PV current (Amperes) */
    int32_t pv_power; /* PV power (Watts) */
    int32_t pv_energy_total; /* Total energy generated by PV (Watt-hours) */
    int32_t grid_vol; /* Grid voltage (Volts) */
    int32_t grid_vol_max; /* Maximum grid voltage (Volts) */
    int32_t grid_freq; /* Grid frequency (Hertz) */
    int32_t grid_p; /* Grid active power (Watts) */
    int32_t grid_q; /* Grid reactive power (VAR) */
    int32_t grid_i; /* Grid current (Amperes) */
    int32_t grid_pf; /* Grid power factor */
    int32_t pv_temp; /* PV temperature */
    int32_t pv_run_status; /* PV running status */
    int32_t pv_fault_num; /* PV fault number */
    int32_t pv_fault_cnt; /* PV fault count */
    int32_t pv_warning_cnt; /* PV warning count */
    int32_t pv_link_status; /* PV link status */
    int32_t pv_send_power; /* PV send power (Watts) */
    int32_t pv_receive_power; /* PV received power (Watts) */
    int32_t pv_time; /* PV time */
    int32_t pv_energy; /* PV energy (Watt-hours) */
    int32_t mi_signal; /* Modulation index signal */
} PvDataMO;

typedef struct _RealDataReqDTO {
    char dtu_sn[16]; /* DTU serial number */
    int32_t timestamp; /* Timestamp of the data */
    int32_t device_number; /* Device number */
    int32_t pv_number; /* PV number */
    int32_t package_number; /* Package number */
    int32_t current_package; /* Current package number */
    int32_t csq; /* Carrier Signal Quality (CSQ) */
    pb_size_t meter_data_count;
    MeterDataMO meter_data[2]; /* Meter data array */
    pb_size_t rp_data_count;
    RpDataMO rp_data[4]; /* RpDataMO data array */
    pb_size_t pv_data_count;
    PvDataMO pv_data[4]; /* PvDataMO data array */
    int32_t version; /* Version number */
} RealDataReqDTO;

typedef PB_BYTES_ARRAY_T(24) RealDataResDTO_time_ymd_hms_t;
typedef struct _RealDataResDTO {
    RealDataResDTO_time_ymd_hms_t time_ymd_hms; /* Timestamp in the format YMD_HMS */
    int32_t package_now; /* Package now */
    int32_t error_code; /* Error code indicator */
    int32_t offset; /* Offset value */
    int32_t time; /* Timestamp value */
} RealDataResDTO;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define MeterDataMO_init_default                 {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define RpDataMO_init_default                    {0, 0, 0, 0, 0}
#define PvDataMO_init_default                    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define RealDataReqDTO_init_default              {"", 0, 0, 0, 0, 0, 0, 0, {MeterDataMO_init_default, MeterDataMO_init_default}, 0, {RpDataMO_init_default, RpDataMO_init_default, RpDataMO_init_default, RpDataMO_init_default}, 0, {PvDataMO_init_default, PvDataMO_init_default, PvDataMO_init_default, PvDataMO_init_default}, 0}
#define RealDataResDTO_init_default              {{0, {0}}, 0, 0, 0, 0}
#define MeterDataMO_init_zero                    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define RpDataMO_init_zero                       {0, 0, 0, 0, 0}
#define PvDataMO_init_zero                       {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define RealDataReqDTO_init_zero                 {"", 0, 0, 0, 0, 0, 0, 0, {MeterDataMO_init_zero, MeterDataMO_init_zero}, 0, {RpDataMO_init_zero, RpDataMO_init_zero, RpDataMO_init_zero, RpDataMO_init_zero}, 0, {PvDataMO_init_zero, PvDataMO_init_zero, PvDataMO_init_zero, PvDataMO_init_zero}, 0}
#define RealDataResDTO_init_zero                 {{0, {0}}, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define MeterDataMO_device_kind_tag              1
#define MeterDataMO_meter_sn_tag                 2
#define MeterDataMO_meter_total_power_tag        3
#define MeterDataMO_meter_phase_A_power_tag      4
#define MeterDataMO_meter_phase_B_power_tag      5
#define MeterDataMO_meter_phase_C_power_tag      6
#define MeterDataMO_meter_factor_tag             7
#define MeterDataMO_meter_total_energy_tag       8
#define MeterDataMO_meter_phase_A_energy_tag     9
#define MeterDataMO_meter_phase_B_energy_tag     10
#define MeterDataMO_meter_phase_C_energy_tag     11
#define MeterDataMO_meter_total_consumed_tag     12
#define MeterDataMO_meter_phase_A_consumed_tag   13
#define MeterDataMO_meter_phase_B_consumed_tag   14
#define MeterDataMO_meter_phase_C_consumed_tag   15
#define MeterDataMO_meter_fault_tag              16
#define RpDataMO_rp_sn_tag                       1
#define RpDataMO_rp_signal_tag                   2
#define RpDataMO_rp_channel_tag                  3
#define RpDataMO_rp_link_nub_tag                 4
#define RpDataMO_rp_link_status_tag              5
#define PvDataMO_pv_sn_tag                       1
#define PvDataMO_pv_port_tag                     2
#define PvDataMO_pv_vol_tag                      3
#define PvDataMO_pv_cur_tag                      4
#define PvDataMO_pv_power_tag                    5
#define PvDataMO_pv_energy_total_tag             6
#define PvDataMO_grid_vol_tag                    7
#define PvDataMO_grid_vol_max_tag                8
#define PvDataMO_grid_freq_tag                   9
#define PvDataMO_grid_p_tag                      10
#define PvDataMO_grid_q_tag                      11
#define PvDataMO_grid_i_tag                      12
#define PvDataMO_grid_pf_tag                     13
#define PvDataMO_pv_temp_tag                     14
#define PvDataMO_pv_run_status_tag               15
#define PvDataMO_pv_fault_num_tag                16
#define PvDataMO_pv_fault_cnt_tag                17
#define PvDataMO_pv_warning_cnt_tag              18
#define PvDataMO_pv_link_status_tag              19
#define PvDataMO_pv_send_power_tag               20
#define PvDataMO_pv_receive_power_tag            21
#define PvDataMO_pv_time_tag                     22
#define PvDataMO_pv_energy_tag                   23
#define PvDataMO_mi_signal_tag                   24
#define RealDataReqDTO_dtu_sn_tag                1
#define RealDataReqDTO_timestamp_tag             2
#define RealDataReqDTO_device_number_tag         3
#define RealDataReqDTO_pv_number_tag             4
#define RealDataReqDTO_package_number_tag        5
#define RealDataReqDTO_current_package_tag       6
#define RealDataReqDTO_csq_tag                   7
#define RealDataReqDTO_meter_data_tag            8
#define RealDataReqDTO_rp_data_tag               9
#define RealDataReqDTO_pv_data_tag               10
#define RealDataReqDTO_version_tag               11
#define RealDataResDTO_time_ymd_hms_tag          1
#define RealDataResDTO_package_now_tag           2
#define RealDataResDTO_error_code_tag            3
#define RealDataResDTO_offset_tag                4
#define RealDataResDTO_time_tag                  5

/* Struct field encoding specification for nanopb */
#define MeterDataMO_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    device_kind,       1) \
X(a, STATIC,   SINGULAR, INT64,    meter_sn,          2) \
X(a, STATIC,   SINGULAR, INT32,    meter_total_power,   3) \
X(a, STATIC,   SINGULAR, INT32,    meter_phase_A_power,   4) \
X(a, STATIC,   SINGULAR, INT32,    meter_phase_B_power,   5) \
X(a, STATIC,   SINGULAR, INT32,    meter_phase_C_power,   6) \
X(a, STATIC,   SINGULAR, INT32,    meter_factor,      7) \
X(a, STATIC,   SINGULAR, INT32,    meter_total_energy,   8) \
X(a, STATIC,   SINGULAR, INT32,    meter_phase_A_energy,   9) \
X(a, STATIC,   SINGULAR, INT32,    meter_phase_B_energy,  10) \
X(a, STATIC,   SINGULAR, INT32,    meter_phase_C_energy,  11) \
X(a, STATIC,   SINGULAR, INT32,    meter_total_consumed,  12) \
X(a, STATIC,   SINGULAR, INT32,    meter_phase_A_consumed,  13) \
X(a, STATIC,   SINGULAR, INT32,    meter_phase_B_consumed,  14) \
X(a, STATIC,   SINGULAR, INT32,    meter_phase_C_consumed,  15) \
X(a, STATIC,   SINGULAR, INT32,    meter_fault,      16)
#define MeterDataMO_CALLBACK NULL
#define MeterDataMO_DEFAULT NULL

#define RpDataMO_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT64,    rp_sn,             1) \
X(a, STATIC,   SINGULAR, INT32,    rp_signal,         2) \
X(a, STATIC,   SINGULAR, INT32,    rp_channel,        3) \
X(a, STATIC,   SINGULAR, INT32,    rp_link_nub,       4) \
X(a, STATIC,   SINGULAR, INT32,    rp_link_status,    5)
#define RpDataMO_CALLBACK NULL
#define RpDataMO_DEFAULT NULL

#define PvDataMO_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT64,    pv_sn,             1) \
X(a, STATIC,   SINGULAR, INT32,    pv_port,           2) \
X(a, STATIC,   SINGULAR, INT32,    pv_vol,            3) \
X(a, STATIC,   SINGULAR, INT32,    pv_cur,            4) \
X(a, STATIC,   SINGULAR, INT32,    pv_power,          5) \
X(a, STATIC,   SINGULAR, INT32,    pv_energy_total,   6) \
X(a, STATIC,   SINGULAR, INT32,    grid_vol,          7) \
X(a, STATIC,   SINGULAR, INT32,    grid_vol_max,      8) \
X(a, STATIC,   SINGULAR, INT32,    grid_freq,         9) \
X(a, STATIC,   SINGULAR, INT32,    grid_p,           10) \
X(a, STATIC,   SINGULAR, INT32,    grid_q,           11) \
X(a, STATIC,   SINGULAR, INT32,    grid_i,           12) \
X(a, STATIC,   SINGULAR, INT32,    grid_pf,          13) \
X(a, STATIC,   SINGULAR, INT32,    pv_temp,          14) \
X(a, STATIC,   SINGULAR, INT32,    pv_run_status,    15) \
X(a, STATIC,   SINGULAR, INT32,    pv_fault_num,     16) \
X(a, STATIC,   SINGULAR, INT32,    pv_fault_cnt,     17) \
X(a, STATIC,   SINGULAR, INT32,    pv_warning_cnt,   18) \
X(a, STATIC,   SINGULAR, INT32,    pv_link_status,   19) \
X(a, STATIC,   SINGULAR, INT32,    pv_send_power,    20) \
X(a, STATIC,   SINGULAR, INT32,    pv_receive_power,  21) \
X(a, STATIC,   SINGULAR, INT32,    pv_time,          22) \
X(a, STATIC,   SINGULAR, INT32,    pv_energy,        23) \
X(a, STATIC,   SINGULAR, INT32,    mi_signal,        24)
#define PvDataMO_CALLBACK NULL
#define PvDataMO_DEFAULT NULL

#define RealDataReqDTO_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   dtu_sn,            1) \
X(a, STATIC,   SINGULAR, INT32,    timestamp,         2) \
X(a, STATIC,   SINGULAR, INT32,    device_number,     3) \
X(a, STATIC,   SINGULAR, INT32,    pv_number,         4) \
X(a, STATIC,   SINGULAR, INT32,    package_number,    5) \
X(a, STATIC,   SINGULAR, INT32,    current_package,   6) \
X(a, STATIC,   SINGULAR, INT32,    csq,               7) \
X(a, STATIC,   REPEATED, MESSAGE,  meter_data,        8) \
X(a, STATIC,   REPEATED, MESSAGE,  rp_data,           9) \
X(a, STATIC,   REPEATED, MESSAGE,  pv_data,          10) \
X(a, STATIC,   SINGULAR, INT32,    version,          11)
#define RealDataReqDTO_CALLBACK NULL
#define RealDataReqDTO_DEFAULT NULL
#define RealDataReqDTO_meter_data_MSGTYPE MeterDataMO
#define RealDataReqDTO_rp_data_MSGTYPE RpDataMO
#define RealDataReqDTO_pv_data_MSGTYPE PvDataMO

#define RealDataResDTO_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    time_ymd_hms,      1) \
X(a, STATIC,   SINGULAR, INT32,    package_now,       2) \
X(a, STATIC,   SINGULAR, INT32,    error_code,        3) \
X(a, STATIC,   SINGULAR, INT32,    offset,            4) \
X(a, STATIC,   SINGULAR, INT32,    time,              5)
#define RealDataResDTO_CALLBACK NULL
#define RealDataResDTO_DEFAULT NULL

extern const pb_msgdesc_t MeterDataMO_msg;
extern const pb_msgdesc_t RpDataMO_msg;
extern const pb_msgdesc_t PvDataMO_msg;
extern const pb_msgdesc_t RealDataReqDTO_msg;
extern const pb_msgdesc_t RealDataResDTO_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define MeterDataMO_fields &MeterDataMO_msg
#define RpDataMO_fields &RpDataMO_msg
#define PvDataMO_fields &PvDataMO_msg
#define RealDataReqDTO_fields &RealDataReqDTO_msg
#define RealDataResDTO_fields &RealDataResDTO_msg

/* Maximum encoded size of messages (where known) */
#define MeterDataMO_size                         177
#define PvDataMO_size                            273
#define REALDATA_PB_H_MAX_SIZE                   RealDataReqDTO_size
#define RealDataReqDTO_size                      1786
#define RealDataResDTO_size                      70
#define RpDataMO_size                            55

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
