/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "RealData.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(MeterDataMO, MeterDataMO, AUTO)


PB_BIND(RpDataMO, RpDataMO, AUTO)


PB_BIND(PvDataMO, PvDataMO, AUTO)


PB_BIND(RealDataReqDTO, RealDataReqDTO, 2)


PB_BIND(RealDataResDTO, RealDataResDTO, AUTO)



