substitutions:
  name: test_r48

esphome:
  name: ${name}
  min_version: 2024.6.0
  

external_components:
  - source: "github://SeByDocKy/myESPhome/"
    components: [emerson_r48]
    refresh: 0s

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    version: 5.5.1
    platform_version: 55.03.31-2

logger:
  baud_rate: 0
  # level: INFO

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:


ota:
  - platform: esphome

spi:
  id: shared_spi
  clk_pin: GPIO18
  mosi_pin: GPIO23
  miso_pin: GPIO19

canbus:
  - platform: mcp2515
    id: can
    spi_id: shared_spi
    use_extended_id: true
    cs_pin: GPIO5
    can_id: 0x0607FF83
    bit_rate: 125kbps
    mode: NORMAL
    data_rate: 10Mhz

emerson_r48:
  canbus_id: can
  update_interval: 1s

time:
  - platform: sntp
    id: esphome_time
    servers: pool.ntp.org

switch:
  - platform: emerson_r48
    ac_sw:
      name: ${name}_r48_ac_switch_turn_off
      restore_mode: ALWAYS_ON
    dc_sw:
      name: ${name}_r48_dc_switch_turn_off
      restore_mode: ALWAYS_ON
    fan_sw:
      name: ${name}_r48_fan_switch_max
    led_sw:
      name: ${name}_r48_led_switch

binary_sensor:
  - platform: status
    name: ${name}_esp_controller_status


output:
  - platform: emerson_r48
    max_current:
      id: ${name}_max_current

button:
  - platform: emerson_r48
    set_offline_values:
      name: ${name}_r48_set_offline_values

  - platform: restart
    name: ${name}_restart_esp

number:
  - platform: emerson_r48
    output_voltage:
      name: ${name}_r48_set_output_voltage
    max_output_current:
      name: ${name}_r48_max_output_current
      unit_of_measurement: '%'
    max_input_current:
      name: ${name}_r48_max_input_current

sensor:
  - platform: emerson_r48
    output_voltage:
      name: ${name}_r48_output_voltage
      id: r48_output_voltage
    output_current:
      name: ${name}_r48_output_current
      id: r48_output_current  
    output_temp:
      name: ${name}_r48_temperature
    input_voltage:
      name: ${name}_r48_ac_voltage
    max_output_current:
      name: ${name}_r48_dc_max_current
      unit_of_measurement: '%'

  - platform: template
    name: outPower
    id: outpower
    unit_of_measurement: W
    device_class: power
    update_interval: 6s 
    accuracy_decimals: 2
    lambda: |-
      if(id(r48_output_current).state>0) { return ( id(r48_output_current).state * id(r48_output_voltage).state ); } 
      else {return 0;} 