external_components:
  # - source: "github://leodesigner/esphome-emerson-vertiv-r48"
    # components: [emerson_r48]
    # refresh: 0s
    
  - source: 
      type: git
      url: http://github.com/IxioJo/esphome-emerson-vertiv-r48
      # url: github://leodesigner/esphome-emerson-vertiv-r48
      ref: main
    refresh: 0s        
               
canbus:
  - platform: mcp2515
    id: ${emmerson_name}_id
    spi_id: ${emmerson__spid_id}
    use_extended_id: true
    cs_pin: ${emmerson_cs_pin} #GPIO5
    can_id: 0x0607FF83
    bit_rate: 125kbps
    mode: NORMAL
    data_rate: 5Mhz #10Mhz            
            
emerson_r48:
  canbus_id: ${emmerson_name}_id
  update_interval: ${emmerson_update_interval}

switch:
  - platform: emerson_r48
    ac_sw:
      name: ${name}_${emmerson_name}_ac_switch_turn_off
      restore_mode: ALWAYS_ON
    dc_sw:
      name: ${name}_${emmerson_name}_dc_switch_turn_off
      restore_mode: ALWAYS_ON
    fan_sw:
      name: ${name}_${emmerson_name}_fan_switch_max
    led_sw:
      name: ${name}_${emmerson_name}_led_switch
      
button:
  - platform: emerson_r48
    set_offline_values:
      name: ${name}_${emmerson_name}_set_offline_values

number:
  - platform: emerson_r48
    output_voltage:
      name: ${name}_${emmerson_name}_set_output_voltage
      icon: mdi:sine-wave
      unit_of_measurement: 'V'
    max_output_current:
      name: ${name}_${emmerson_name}_max_output_current
      unit_of_measurement: '%'
      icon: mdi:percent
    max_input_current:
      name: ${name}_${emmerson_name}_max_input_current
      unit_of_measurement: 'A'
      icon: mdi:current-ac
       
sensor:

  - platform: emerson_r48
    output_voltage:
      name: ${name}_${emmerson_name}_output_voltage
      id: ${emmerson_name}_output_voltage
      unit_of_measurement: 'V'
      icon: mdi:percent
      accuracy_decimals: 1
    output_current:
      name: ${name}_${emmerson_name}_output_current
      id: ${emmerson_name}_output_current
      unit_of_measurement: 'A'
      icon: mdi:current-dc      
      accuracy_decimals: 1
    output_temp:
      name: ${name}_${emmerson_name}_temperature
      unit_of_measurement: '°C'
      icon: mdi:thermometer
      accuracy_decimals: 1
    input_voltage:
      name: ${name}_${emmerson_name}_ac_voltage
      unit_of_measurement: 'V'
      icon: mdi:sine-wave      
      accuracy_decimals: 1
    max_output_current:
      name: ${name}_${emmerson_name}_dc_max_current
      unit_of_measurement: '%'
      icon: mdi:percent
      
  - platform: template
    name: ${name}_${emmerson_name}_outpower
    id: ${emmerson_name}_outpower
    unit_of_measurement: W
    device_class: power
    update_interval: ${emmerson_template_update_interval} 
    accuracy_decimals: 1
    icon: mdi:power
    lambda: |-
      if(id(${emmerson_name}_output_current).state>0) { return ( id(${emmerson_name}_output_current).state * id(${emmerson_name}_output_voltage).state ); } 
      else {return 0;}      