external_components:
  - source: "github://SeByDocKy/myESPhome/"
    components: [dualpidpcm]
    refresh: 0s
    
dualpidpcm:
  - id: ${dualpidpcm_id}
    input_id: ${dualpidpcm_name}_input_smoothed 
    battery_voltage_id: ${dualpidpcm_battery_voltage_id}
    charging_output_id: ${dualpidpcm_charging_output_id}
    discharging_output_id: ${dualpidpcm_discharging_output_id}
    discharge_charge_switch_id: ${dualpidpcm_discharge_charge_switch_id}
    onoff_switch_id: ${dualpidpcm_onoff_switch_id}
    current_min_charging: ${dualpidpcm_current_min_charging}
    current_min_discharging: ${dualpidpcm_current_min_discharging}
    
sensor:
  - platform: copy
    source_id: ${dualpidpcm_input_id}
    name: ${name}_${dualpidpcm_name}_input_smoothed
    id: ${dualpidpcm_name}_input_smoothed
    device_class: energy
    icon: mdi:power
    unit_of_measurement: 'W'
    accuracy_decimals: 1
    filters:
      - sliding_window_moving_average:
          window_size: ${dualpidpcm_windows_size}
          send_every: 1
          
#   - platform: dualpidpcm
#     dualpidpcm_id: ${dualpidpcm_id}
#     error: 
#       name: ${name}_${dualpidpcm_name}_error    
#     output_charging: 
#       name: ${name}_${dualpidpcm_name}_output_charging
#     output_discharging: 
#       name: ${name}_${dualpidpcm_name}_output_discharging      
#     input:
#       name: ${name}_${dualpidpcm_name}_input  


# switch:
#   - platform: dualpidpcm
#     dualpidpcm_id: ${dualpidpcm_id}
#     activation: 
#       name: ${name}_${dualpidpcm_name}_activation
#       id: ${dualpidpcm_name}_activation
#     manual_override: 
#       name: ${name}_${dualpidpcm_name}_manual_override
#       id:  ${dualpidpcm_name}_manual_override
#     pid_mode: 
#       name: ${name}_${dualpidpcm_name}_pid_mode
#       id:  ${dualpidpcm_name}_pid_mode
#     reverse: 
#       name: ${name}_${dualpidpcm_name}_reverse
#       id:  ${dualpidpcm_name}_reverse
      
# number:
#   - platform: dualpidpcm
#     dualpidpcm_id: ${dualpidpcm_id}
#     setpoint:
#       name: ${name}_${dualpidpcm_name}_setpoint
#     starting_battery_voltage: 
#       name: ${name}_${dualpidpcm_name}_starting_battery_voltage
#     kp_charging: 
#       name: ${name}_${dualpidpcm_name}_kp_charging
#     ki_charging: 
#       name: ${name}_${dualpidpcm_name}_ki_charging
#     kd_charging: 
#       name: ${name}_${dualpidpcm_name}_kd_charging
#     kp_discharging: 
#       name: ${name}_${dualpidpcm_name}_kp_discharging
#     ki_discharging: 
#       name: ${name}_${dualpidpcm_name}_ki_discharging
#     kd_discharging: 
#       name: ${name}_${dualpidpcm_name}_kd_discharging      
#     output_min_charging: 
#       name: ${name}_${dualpidpcm_name}_output_min_charging
#     output_max_charging: 
#       name: ${name}_${dualpidpcm_name}_output_max_charging
#     output_min_discharging: 
#       name: ${name}_${dualpidpcm_name}_output_min_discharging
#     output_max_discharging: 
#       name: ${name}_${dualpidpcm_name}_output_max_discharging
