external_components:
  - source: "github://SeByDocKy/myESPhome/"
    components: [jsy1039]
    refresh: 0s

globals:
  - id: ${jsy1039_name}_pos_energy_yesterday_global
    type: float
    restore_value: yes
    
  - id: ${jsy1039_name}_neg_energy_yesterday_global
    type: float
    restore_value: yes    
       
time:
  - platform: homeassistant #sntp
    id: !extend my_time
    on_time:
      - seconds: ${my_second}
        minutes: ${my_minute}
        hours: ${my_hours}
        then:  
          - globals.set:
              id: ${jsy1039_name}_pos_energy_yesterday_global
              value: !lambda return ( id(${jsy1039_name}_pos_energy_yesterday_global) =  float( id(${jsy1039_name}_pos_energy_today).state) );

          - globals.set:
              id: ${jsy1039_name}_neg_energy_yesterday_global
              value: !lambda return ( id(${jsy1039_name}_neg_energy_yesterday_global) =  float( id(${jsy1039_name}_neg_energy_today).state) );                
                
sensor:
  - platform: jsy1039
    id: ${jsy1039_name}_id 
    modbus_id: ${jsy1039_modbus_id}
    address: ${jsy1039_address}
    update_interval: ${jsy1039_update_interval}
    current:
      name: ${name}_${jsy1039_name}_current
      accuracy_decimals: 1
    voltage:
      name: ${name}_${jsy1039_name}_voltage
      accuracy_decimals: 1
    power:
      name: ${name}_${jsy1039_name}_power
      id: ${jsy1039_name}_power
      accuracy_decimals: 1
    frequency:
      name: ${name}_${jsy1039_name}_frequency
      accuracy_decimals: 1
    power_factor:
      name: ${name}_${jsy1039_name}_power_factor
      accuracy_decimals: 2
    pos_energy:
      name: ${name}_${jsy1039_name}_pos_energy
      id: ${jsy1039_name}_pos_energy
      accuracy_decimals: 1
    neg_energy:
      name: ${name}_${jsy1039_name}_neg_energy
      id: ${jsy1039_name}_neg_energy
      accuracy_decimals: 1


  - platform: template
    name: ${name}_${jsy1039_name}_pos_power
    id: ${jsy1039_name}_pos_power
    unit_of_measurement: 'W'
    accuracy_decimals: 1
    update_interval: ${jsy1039_template_update}
    icon: mdi:power
    lambda: |-
      if(id(${jsy1039_name}_power).state > 0.0){
        return (id(${jsy1039_name}_power).state);
      }
      else{
        return 0.0;
      }      
  - platform: total_daily_energy
    name: ${name}_${jsy1039_name}_pos_energy_today
    id: ${jsy1039_name}_pos_energy_today
    power_id: ${jsy1039_name}_pos_power
    unit_of_measurement: 'kWh'
    accuracy_decimals: 1
    method: trapezoid
    filters:
      - multiply: 0.001
    icon: mdi:counter
    
  - platform: template
    name: ${name}_${jsy1039_name}_pos_energy_yesterday
    id: ${jsy1039_name}_pos_energy_yesterday
    unit_of_measurement: 'kWh'
    accuracy_decimals: 1
    icon: mdi:counter
    update_interval: ${jsy1039_template_update}
    lambda: |-
      return (id(${jsy1039_name}_pos_energy_yesterday).state = id(${jsy1039_name}_pos_energy_yesterday_global));

  - platform: template
    name: ${name}_${jsy1039_name}_neg_power
    id: ${jsy1039_name}_neg_power
    unit_of_measurement: 'W'
    accuracy_decimals: 1
    update_interval: ${jsy1039_template_update}
    icon: mdi:power
    lambda: |-
      if(id(${jsy1039_name}_power).state <= 0.0){
        return (id(${jsy1039_name}_power).state);
      }
      else{
        return 0.0;
      }

  - platform: total_daily_energy
    name: ${name}_${jsy1039_name}_neg_energy_today
    id: ${jsy1039_name}_neg_energy_today
    power_id: ${jsy1039_name}_neg_power
    unit_of_measurement: 'kWh'
    accuracy_decimals: 1
    method: trapezoid
    filters:
      - multiply: 0.001
    icon: mdi:counter
    
  - platform: template
    name: ${name}_${jsy1039_name}_neg_energy_yesterday
    id: ${jsy1039_name}_neg_energy_yesterday
    unit_of_measurement: 'kWh'
    accuracy_decimals: 1
    icon: mdi:counter
    update_interval: ${jsy1039_template_update}
    lambda: |-
      return (id(${jsy1039_name}_neg_energy_yesterday).state = id(${jsy1039_name}_neg_energy_yesterday_global));    



