globals:
  - id: ${hms_inverter_name}_energy_yesterday_global
    type: float
    restore_value: yes
    
time:
  - platform: homeassistant #sntp
    id: !extend my_time
    on_time:
      - seconds: ${my_second}
        minutes: ${my_minute}
        hours: ${my_hours}
        then:  
          - globals.set:
              id: ${hms_inverter_name}_energy_yesterday_global
              value: !lambda return ( id(${hms_inverter_name}_energy_yesterday_global) =  float( id(${hms_inverter_name}_energy_today).state) );

fan:
  - platform: speed
    id: ${hms_inverter_name}_command
    name: ${name}_${hms_inverter_name}_command
    output: ${hms_inverter_name}_percent_output

hms_inverter:
  id: !extend ${hms_inverter_id}
  inverters:
    - id: ${hms_inverter_name}_id  #!extend
      serial: ${hms_inverter_sn} # Serial No of your inverter 
      rssi:
        name: ${name}_${hms_inverter_name}_rssi  # Sensor
      limit_percent: # Number Entity 0 - 100%
        name: ${name}_${hms_inverter_name}_percent_power_limit
      limit_absolute: # Number Entity 0 - 2500 W
        name: ${name}_${hms_inverter_name}_absolute_power_limit
      palevel:
        name: ${name}_${hms_inverter_name}_palevel  
      percent_output:
        id: ${hms_inverter_name}_percent_output
      restart:
        name: ${name}_${hms_inverter_name}_restart
        id: ${hms_inverter_name}_restart
      reachable: # Binary Sensor
        name: ${name}_${hms_inverter_name}_reachable
        id: ${hms_inverter_name}_reachable
      producing: # Binary Sensor
        name: ${name}_${hms_inverter_name}_producing
        id: ${hms_inverter_name}_producing
      dc_channels:
        - power: # Power in W
            name: ${name}_${hms_inverter_name}_pv0_power
          current: # Current in A
            name: ${name}_${hms_inverter_name}_pv0_current
            icon: mdi:current-dc
          voltage: # Voltage in V
            name: ${name}_${hms_inverter_name}_pv0_voltage
          energy: 
            name: ${name}_${hms_inverter_name}_pv0_energy_today
            device_class: energy
            icon: mdi:counter
            unit_of_measurement: 'kWh'
            filters: 
              - multiply: 0.001
        - power:
            name: ${name}_${hms_inverter_name}_pv1_power
          current: # Current in A
            name: ${name}_${hms_inverter_name}_pv1_current
            icon: mdi:current-dc
          voltage: # Voltage in V
            name: ${name}_${hms_inverter_name}_pv1_voltage
          energy: 
            name: ${name}_${hms_inverter_name}_pv1_energy_today
            device_class: energy
            icon: mdi:counter
            unit_of_measurement: 'kWh'
            filters: 
              - multiply: 0.001
              
        - power:
            name: ${name}_${hms_inverter_name}_pv2_power
          current: # Current in A
            name: ${name}_${hms_inverter_name}_pv2_current
            icon: mdi:current-dc
          voltage: # Voltage in V
            name: ${name}_${hms_inverter_name}_pv2_voltage
          energy: 
            name: ${name}_${hms_inverter_name}_pv2_energy_today
            device_class: energy
            icon: mdi:counter
            unit_of_measurement: 'kWh'
            filters: 
              - multiply: 0.001
              
        - power:
            name: ${name}_${hms_inverter_name}_pv3_power
          current: # Current in A
            name: ${name}_${hms_inverter_name}_pv3_current
            icon: mdi:current-dc
          voltage: # Voltage in V
            name: ${name}_${hms_inverter_name}_pv3_voltage
          energy: 
            name: ${name}_${hms_inverter_name}_pv3_energy_today
            device_class: energy
            icon: mdi:counter
            unit_of_measurement: 'kWh'
            filters: 
              - multiply: 0.001
      ac_channel:
        power:
          name: ${name}_${hms_inverter_name}_ac_power
        energy: 
          name: ${name}_${hms_inverter_name}_ac_energy_today
          device_class: energy
          icon: mdi:counter
          unit_of_measurement: 'kWh'
          filters: 
            - multiply: 0.001
      inverter_channel:
        temperature:
          name: ${name}_${hms_inverter_name}_temperature
        power:
          name: ${name}_${hms_inverter_name}_inverter_power
        energy: # Today's Energy in Wh
          name: ${name}_${hms_inverter_name}_inverter_energy_today
          device_class: energy
          icon: mdi:counter
          unit_of_measurement: 'kWh'
          filters: 
            - multiply: 0.001

sensor:
  - platform: total_daily_energy
    name: ${name}_${hms_inverter_name}_energy_today
    id: ${hms_inverter_name}_energy_today
    power_id: ${hms_inverter_name}_inverter_power
    unit_of_measurement: 'kWh'
    accuracy_decimals: 1
    method: right
    restore: true
    filters:
        # Multiplication factor from W to kW is 0.001
      - multiply: 0.001
    icon: mdi:counter
    
  - platform: template
    name: ${name}_${hms_inverter_name}_energy_yesterday
    id: ${hms_inverter_name}_energy_yesterday
    unit_of_measurement: 'kWh'
    accuracy_decimals: 1
    icon: mdi:counter
    # update_interval: ${hms_inverter_template_update}
    lambda: |-
      return (id(${hms_inverter_name}_energy_yesterday).state = id(${hms_inverter_name}_energy_yesterday_global));

