substitutions:
  name: "deye_mono"
  device_description: "ESPhome Deye hybrid inverter"
  my_hours: '23'
  my_minute: '59'
  my_second: '59'
  baud_rate: 9600 
 
esphome:
  name: ${name}
  comment: ${device_description}
  min_version: 2026.1.0


esp32:
  board: esp32-s3-devkitc-1
  cpu_frequency: 240Mhz
  framework:
    type: esp-idf
    version: 5.5.2
    platform_version: 55.03.36

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "battery_bidirectional"
    password: !secret ap_password
    
# web_server:
  # port: 80    
    
    
time:
  - platform: sntp
    id: my_time    

api:
  batch_delay: 50ms

ota:
  - platform: esphome
  
logger:
  # hardware_uart: USB_SERIAL_JTAG
  level: verbose
  # level: none
         
uart: 
  - id: uart_0
    tx_pin: GPIO05
    rx_pin: GPIO04
    baud_rate: ${baud_rate}
    parity: none
    data_bits: 8
    stop_bits: 1

debug:
  update_interval: 5s


sensor:

  - platform: wifi_signal
    name: ${name}_wifi_power
    id: wifi_power
    update_interval: 5s
    
  - platform: uptime
    id: uptime_sec
    
  - platform: debug
    free:
      name: ${name}_heap_free
    loop_time:
      name: ${name}_loop_time
    
    
packages: 

          
  modbus:
    url: https://github.com/SeByDocKy/pvbrain2/
    ref: main
    refresh: 10s
    files: 
      - path: 'pvbrain2/base/device_modbus.yaml'
        vars:
          modbus_id: 'modbus_id'
          modbus_uart_id: uart_0
          modbus_send_wait_time: '100ms'          
          
  deye_main:
    url: https://github.com/SeByDocKy/pvbrain2/
    ref: main
    refresh: 10s
    files: 
      - path: 'pvbrain2/inverter/deye/device_deye.yaml'
        vars:
          inverter_name: 'deye'
          inverter_modbus_id: 'modbus_id'
          inverter_modbus_address: '1'
          inverter_modbus_throttle: '100ms'
          inverter_update_interval: '2s'
          inverter_template_update: '2s'
          inverter_text_update: '5s'
          
  deye_advanced:
    url: https://github.com/SeByDocKy/pvbrain2/
    ref: main
    refresh: 10s
    files: 
      - path: 'pvbrain2/inverter/deye/device_deye_advanced.yaml'
        vars:
          inverter_name: 'deye'
          inverter_modbus_id: 'modbus_id'
          inverter_modbus_address: '1'
          inverter_modbus_throttle: '100ms'
          inverter_update_interval: '2s'
          inverter_template_update: '2s'
          inverter_text_update: '5s'      