substitutions:
  name: "modbus-sniffer"

esphome:
  name: ${name}
  min_version: 2025.10.0

esp32:
  board: esp32-s3-devkitc-1
  cpu_frequency: 240MHz
  framework:
    type: esp-idf
    version: 5.5.1
    platform_version: 55.03.31-2
    advanced:
      enable_idf_experimental_features: yes

# Configuration WiFi
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# API et OTA
api:

logger:
  hardware_uart: USB_SERIAL_JTAG
  level: verbose

ota:
  - platform: esphome
  

# Configuration UART pour le bus Modbus
uart:
  - id: uart_0
    tx_pin: GPIO05
    rx_pin: GPIO04
    baud_rate: 9600
    # data_bits: 8
    # stop_bits: 1
    # parity: NONE
    # debug:
      # direction: BOTH  # Capture RX et TX
      # dummy_receiver: true  # Affiche même sans composant utilisant l'UART
      # after:
        # delimiter: "\n"  # Optionnel : affiche ligne par ligne
      # sequence:
        # - lambda: UARTDebug::log_hex(direction, bytes, ':');  

# Composant externe
external_components:
  - source: "github://SeByDocKy/myESPhome/"
    components: [modbus_sniffer]
    refresh: 0s

# Hub Modbus Sniffer
modbus_sniffer:
  - id: my_sniffer
    uart_id: uart_0
    address: 1  # Optionnel: filtre sur l'adresse esclave
    
sensor:
  # Exemple 1: Lecture d'un registre 16 bits signé (WORD)
  
  - platform: modbus_sniffer
    modbus_sniffer_id: my_sniffer
    name: ${name}_humidite
    id: humidite
    address: 0x0000
    value_type: S_WORD
    register_type: holding
    unit_of_measurement: '%'
    icon: mdi:percent
    accuracy_decimals: 1
    filters:
      - multiply: 0.1  
  
  - platform: modbus_sniffer
    modbus_sniffer_id: my_sniffer
    name: ${name}_temperature
    id: temperature
    address: 0x0001
    value_type: S_WORD
    register_type: holding
    unit_of_measurement: '°C'
    icon: mdi:thermometer
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
      
  - platform: modbus_sniffer
    modbus_sniffer_id: my_sniffer
    name: ${name}_modbus_address
    register_type: holding
    address: 0x07D0
    value_type: S_WORD
    icon: mdi:numeric
    accuracy_decimals: 0
    
  - platform: modbus_sniffer
    modbus_sniffer_id: my_sniffer
    name: ${name}_baudrate
    register_type: holding
    address: 0x07D1
    value_type: S_WORD
    icon: mdi:numeric
    accuracy_decimals: 0   
 

  # # Exemple 2: Lecture d'un registre 16 bits signé
  # - platform: modbus_sniffer
    # modbus_sniffer_id: my_sniffer
    # name: ${name}_temperature
    # id: temperature
    # address: 0x0200
    # value_type: S_WORD
    # register_type: read
    # unit_of_measurement: "°C"
    # accuracy_decimals: 1
    # device_class: temperature
    # state_class: measurement
    # filters:
      # - multiply: 0.1  # Si la valeur est en dixièmes de degré

  # # Exemple 3: Lecture d'un registre 32 bits (2 registres consécutifs)
  # - platform: modbus_sniffer
    # modbus_sniffer_id: my_sniffer
    # name: ${name}_energy_total
    # id: energy
    # address: 0x0300
    # value_type: U_DWORD  # 32-bit unsigned
    # register_type: holding
    # unit_of_measurement: "kWh"
    # accuracy_decimals: 2
    # device_class: energy
    # state_class: total_increasing

  # # Exemple 4: Lecture d'un float 32 bits
  # - platform: modbus_sniffer
    # modbus_sniffer_id: my_sniffer
    # name: ${name}_voltage
    # id: voltage
    # address: 0x0400
    # value_type: FP32  # Float 32-bit
    # register_type: holding
    # unit_of_measurement: "V"
    # accuracy_decimals: 2
    # device_class: voltage
    # state_class: measurement

  # # Exemple 5: Float 32 bits avec registres inversés
  # - platform: modbus_sniffer
    # modbus_sniffer_id: my_sniffer
    # name: ${name}_current
    # id: current
    # address: 0x0500
    # value_type: FP32_R  # Float 32-bit reversed (low word first)
    # register_type: holding
    # unit_of_measurement: "A"
    # accuracy_decimals: 3
    # device_class: current
    # state_class: 
    
    
# Binary Sensors Modbus
# binary_sensor:
  # # Exemple 1: Vérifier un bit spécifique (bit 0)
  # - platform: modbus_sniffer
    # modbus_sniffer_id: my_sniffer
    # name: ${name}_relay_1_status
    # id: relay1
    # address: 0x0600
    # bitmask: 0x0001  # Bit 0
    # register_type: holding

  # # Exemple 2: Vérifier bit 3
  # - platform: modbus_sniffer
    # modbus_sniffer_id: my_sniffer
    # name: ${name}_alarm_active
    # id: alarm
    # address: 0x0601
    # bitmask: 0x0008  # Bit 3 (0x0008 = 0b0000000000001000)
    # register_type: holding
    # device_class: problem    