#################### Compile with ESPhome < 2025.6.3 ##################


substitutions:
  name: test_hms

esphome:
  name: ${name}

  platformio_options:  
     build_unflags:
      - -Werror=all
     build_flags:
      -DBOARD_HAS_PSRAM
      # -DPIN_MAPPING_REQUIRED=1
        
esp32:
  board: esp32dev
  cpu_frequency: 240Mhz
  framework:
    type: arduino # platformio/espressif32@5.4.0)
    # version: 3.0.4  ##  ~3.20005.0
    # platform_version: 53.3.13
   
external_components:
  - source: "github://SeByDocKy/myESPhome/"
    components: [hoymiles_inverter]
    refresh: 0s
            
logger:
  level: debug

# Enable Home Assistant API
api:
  batch_delay: 50ms

ota:
  - platform: esphome

time:
  - platform: sntp
    id: homeassistant_time

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "HMS Hotspot"
    password: "eVt5yd7PvHjS"
    
        
hoymiles_inverter:
  id: hms_id
  update_interval: '3s'
  pins: 
    clk: GPIO18
    cs: GPIO21
    fcs: GPIO22
    sdio: GPIO19
    gpio2: GPIO27
    gpio3: GPIO32    
    
packages: 

  hoymiles1: 
    url: https://github.com/SeByDocKy/myESPhome/
    ref: main
    refresh: 0s
    files:
      - path: 'code/device_hms_2t.yaml' 
        vars:
          hoymiles_id: 'hms_id'
          hoymiles_name: 'hms1_1000'
          hoymiles_inverter_sn: !secret hms1000_sn1

  hoymiles2: 
    url: https://github.com/SeByDocKy/myESPhome/
    ref: main
    refresh: 0s
    files:
      - path: 'code/device_hms_4t.yaml' 
        vars:
          hoymiles_id: 'hms_id'
          hoymiles_name: 'hms2_2000'
          hoymiles_inverter_sn: !secret hms2000_sn1          

