substitutions:
  name: test_hms_regulation

esphome:
  name: ${name}

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    version: 5.5.1
    platform_version: 55.03.31-1
    
logger:
  # baud_rate: 0
  level: verbose    
  
ota:
  - platform: esphome  

external_components:
  - source: "github://SeByDocKy/myESPhome/"
    components: [hms_regulation]
    refresh: 0s
    
api:
  batch_delay: 50ms

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

time:
  - platform: homeassistant
    id: homeassistant_time  

# uart:
  # - id: uart_0
    # tx_pin: GPIO01
    # rx_pin: GPIO03
    # baud_rate: 9600
    # stop_bits: 1

# modbus:
   # id: modbus_0
   # uart_id: uart_0
   # send_wait_time: 100ms
   

# modbus_controller:
  # - id: controller_0
    # address: 1
    # modbus_id: modbus_0
    # command_throttle: 50ms
    # setup_priority: -10
    # update_interval: 3s



# output:    
  # - platform: template
    # id: fake_power
    # type: float
    # write_action:
      # - lambda: 'return;'

# fan:
  # - platform: speed
    # id: fake_power_command
    # name: ${name}_fake_power_command
    # output: fake_power

button:
  - platform: restart
    name: ${name}_restart

hms_regulation:
  - id: my_hms_regulation1
    input_id: fake_input_id  
    output_id: hms1_1000_percent_output
          
sensor:
  - platform: hms_regulation
    hms_regulation_id: my_hms_regulation1
    error: 
      name: ${name}_regulation_error    
    output: 
      name: ${name}_output
   
  - platform: wifi_signal
    name: ${name}_wifi_power
    id: wifi_power
    update_interval: 5s
    
  - platform: uptime
    id: uptime_sec  
   
  - platform: template
    name: ${name}_fake_input_power
    id: fake_input_power

      
switch:
  - platform: hms_regulation
    hms_regulation_id: my_hms_regulation1
    activation: 
      name: ${name}_activation
      id: activation
    manual_override: 
      name: ${name}_manual_override
      id: manual_override
    pid_mode: 
      name: ${name}_pid_mode
      id: pid_mode
          
number:
  - platform: hms_regulation
    hms_regulation_id: my_hms_regulation1
    setpoint: 
      name: ${name}_setpoint
    kp: 
      name: ${name}_kp
    ki: 
      name: ${name}_ki
    kd: 
      name: ${name}_kd
    output_min: 
      name: ${name}_output_min
    output_max: 
      name: ${name}_output_max

  - platform: template
    name: ${name}_fake_input_power_number  
    id: fake_input_power_number
    optimistic: true
    icon: mdi:numeric
    min_value: 0.0
    max_value: 3000
    step: 10
    mode: 'slider'
    initial_value: 0.0
    restore_value: true
    on_value:
       then:
         - output.set_level:
             id: fake_input_power
             level: !lambda 'return x;'
