# Exemple de configuration avec packet_transport
# IMPORTANT: Nécessite les fichiers packet_transport supplémentaires

esphome:
  name: lora-sensor-node
  platform: ESP32
  board: esp32dev

logger:
  level: DEBUG

# Configuration UART pour le RYLR998
uart:
  id: uart_bus
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 115200

# Configuration du module RYLR998
rylr998:
  id: lora
  uart_id: uart_bus
  address: 101
  frequency: 868MHz
  spreading_factor: 9
  signal_bandwidth: 125kHz
  network_id: 10
  tx_power: 14

# Configuration du packet transport
# NOTE: Cette section nécessite les fichiers packet_transport.py,
# rylr998_packet_transport.h et rylr998_packet_transport.cpp
packet_transport:
  platform: rylr998
  update_interval: 30s
  encryption: "MySecretKey123"
  sensors:
    - room_temperature

# Capteur à transmettre via LoRa
sensor:
  - platform: dht
    pin: GPIO4
    temperature:
      name: "Température"
      id: room_temperature
    humidity:
      name: "Humidité"
