substitutions:
  name: "test_rylr998"
  name_controller: "lora_meter"
  device_description: "RYLR998 LoRa module over UART"
  my_hours: '23'
  my_minute: '59'
  my_second: '59'
  baud_rate: 115200
 
esphome:
  name: ${name}
  comment: ${device_description}
  min_version: 2026.1.0


esp32:
  board: esp32-s3-devkitc-1
  cpu_frequency: 240Mhz
  framework:
    type: esp-idf
    version: 5.5.2
    platform_version: 55.03.36

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "battery_bidirectional"
    password: !secret ap_password
    
time:
  - platform: sntp
    id: my_time    

api:
  batch_delay: 50ms

ota:
  - platform: esphome
  
logger:
  # hardware_uart: USB_SERIAL_JTAG
  level: verbose
  # level: none
    
external_components:
  - source: "github://SeByDocKy/myESPhome/"
    components: [rylr998]
    refresh: 10s
    
uart:
  id: uart_bus
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: ${baud_rate}

rylr998:
  id: lora
  uart_id: uart_bus
  address: 100
  frequency: 868MHz
  spreading_factor: 9
  signal_bandwidth: 125kHz
  coding_rate: 1
  preamble_length: 12
  network_id: 10
  tx_power: 14
  on_packet:
    then:
      - logger.log:
          format: "Paquet reçu: RSSI=%d SNR=%d"
          args: ['rssi', 'snr']
      - lambda: |-
          std::string msg(data.begin(), data.end());
          ESP_LOGI("main", "Données reçues: %s", msg.c_str());

# Bouton pour envoyer un message de test
button:
  - platform: template
    name: "Envoyer Test LoRa"
    on_press:
      - rylr998.send_packet:
          id: lora
          destination: 200
          data: [0x48, 0x45, 0x4C, 0x4C, 0x4F]
      - logger.log: "Message envoyé!"
      
      
packet_transport:
  platform: rylr998
  update_interval: 30s
  encryption: "MySecretKey123"
  sensors:
    - room_temperature
  providers:
    - name: ${name_controller}
      encryption: "loralora"

# Capteur à transmettre via LoRa
sensor:
  - platform: dht
    pin: GPIO4
    temperature:
      name: "Température"
      id: room_temperature
    humidity:
      name: "Humidité"
 
  - platform: packet_transport
    provider: ${name_controller}
    id: local_active_power
    remote_id: active_power 
      
