substitutions:
  name: "test_rylr998"
  # name_controller: "lora_meter"
  device_description: "RYLR998 LoRa module over UART"
  my_hours: '23'
  my_minute: '59'
  my_second: '59'
  baud_rate: 115200
 
esphome:
  name: ${name}
  comment: ${device_description}
  min_version: 2025.10.1


esp32:
  board: esp32-s3-devkitc-1
  cpu_frequency: 240Mhz
  framework:
    type: esp-idf
    version: 5.5.2
    platform_version: 55.03.36

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "battery_bidirectional"
    password: !secret ap_password
    
time:
  - platform: sntp
    id: my_time    

api:
  batch_delay: 50ms

ota:
  - platform: esphome
  
logger:
  # hardware_uart: USB_SERIAL_JTAG
  level: verbose
  # level: none
    
external_components:
  - source: "github://SeByDocKy/myESPhome/"
    components: [rylr998]
    refresh: 10s
    
uart:
  id: uart_bus
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: ${baud_rate}

rylr998:
  id: lora
  uart_id: uart_bus
  address: 100
  frequency: 915MHz
  spreading_factor: 9
  signal_bandwidth: 125kHz
  coding_rate: 1
  preamble_length: 12
  network_id: 18
  tx_power: 22    
