substitutions:
  name: test-hoymiles

esphome:
  name: ${name}


esp32:
  board: esp32dev
  cpu_frequency: 240Mhz
  framework:
    type: arduino
  # framework:
    # type: esp-idf
    # version: 5.5.1
    # platform_version: 55.03.30-2
   
external_components:

  - source: "github://SeByDocKy/myESPhome/"
    components: [hoymiles_inverter]
    refresh: 0s
   
logger:
  baud_rate: 0

# Enable Home Assistant API
api:
  batch_delay: 50ms

ota:
  - platform: esphome

time:
  - platform: homeassistant
    id: homeassistant_time

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Hoymiles Fallback Hotspot"
    password: "eVt5yd7PvHjS"


hoymiles_inverter:
  pins: # Set your own pins
    sdio: GPIO19
    clk: GPIO18
    cs: GPIO21
    fcs: GPIO22
    gpio2: GPIO27
    gpio3: GPIO32
  inverters:
    - serial: "11223344556677" # Serial No of your inverter
      limit_percent: # Number Entity 0 - 100%
        name: ${name}_percent_limit
      limit_absolute: # Number Entity 0 - 2500 W
        name: ${name}_absolute_limit
      reachable: # Binary Sensor
        name: ${name}_reachable
      dc_channels:
        - power: # Power in W
            name: ${name}_channel_0_power
          current: # Current in A
            name: ${name}_channel_0_current
          voltage: # Voltage in V
            name: ${name}_channel_0_voltage
        - power:
            name: ${name}_channel_1_power
      ac_channel:
        power:
          name: ${name}_ac_power
      inverter_channel:
        power:
          name: ${name}_inverter_power
        energy: # Today's Energy in Wh
          name: ${name}_inverter_energy


