"""Register tables for the Anker SOLIX Solarbank family (GENERATED - do not edit by hand).

Generated by tools/gen_registers.py from the device configuration files of
https://github.com/anker-charging/ha-anker-solix-official (custom_components/anker_solix_official/config),
integration version 1.5.0.
The register definitions are Copyright (c) 2026 Anker Innovations, MIT License (see that repository).

Per ESPHome platform: key -> specification (every model of the family shares the same register map).
  register/count : first register and number of 16-bit registers
  rtype          : 'read' = input registers (function code 04), 'holding' = holding registers (03)
  vtype          : SensorValueType name of modbustcp_controller (32-bit values are big-endian)
  scan           : polling class, 'high' (update_interval) or 'low' (low_priority_interval)
"""

MODEL_NAMES = {'max': 'Anker SOLIX Solarbank Max',
 'max_ac': 'Anker SOLIX Solarbank Max AC',
 'sb4_e5000_pro': 'Anker SOLIX Solarbank 4 E5000 Pro',
 'xe': 'Anker SOLIX XE'}

MODEL_NOTES = {'max': 'same register map as the Max AC, not validated by me',
 'max_ac': 'validated on hardware by the HA integration users (Solarbank Max AC)',
 'sb4_e5000_pro': 'same register map as the Max AC, not validated by me',
 'xe': 'same register map as the Max AC, not validated by me'}

# Product codes (characters 4..6 of a 16 digit serial number, 4..7 of a 17 digit one) of each model
PRODUCT_CODES = {'max': {'codes': {'DMY6': 'Anker SOLIX Solarbank Max',
                   'DN9U': 'Anker SOLIX Solarbank Max',
                   'DNMT': 'Anker SOLIX XE',
                   'DNN4': 'Anker SOLIX XE',
                   'DPP5': 'Anker SOLIX XE',
                   'DPTK': 'Anker SOLIX Solarbank Max'},
         'default': 'Anker SOLIX Solarbank Max'},
 'max_ac': {'codes': {'DMWH': 'Anker SOLIX Solarbank Max AC',
                      'DMXU': 'Anker SOLIX Solarbank Max AC',
                      'DNMS': 'Anker SOLIX XE AC',
                      'DNN3': 'Anker SOLIX XE AC',
                      'DPP4': 'Anker SOLIX XE AC',
                      'E25H': 'Anker SOLIX Solarbank Max AC'},
            'default': 'Anker SOLIX Solarbank Max AC'},
 'sb4_e5000_pro': {'codes': {'DN7M': 'Anker SOLIX Solarbank 4 E5000 Pro',
                             'DPM4': 'Anker SOLIX Solarbank 4 E5000 Pro'},
                   'default': 'Anker SOLIX Solarbank 4 E5000 Pro'},
 'xe': {'codes': {'DRE4': 'Anker SOLIX XE', 'E3DS': 'Anker SOLIX XE'}, 'default': 'Anker SOLIX XE'}}

# One register map for every model
_SOLARBANK = {
    "sensor": {
        "pcs_pv_power": {'register': 10002, 'count': 2, 'vtype': 'S_DWORD', 'rtype': 'read', 'icon': 'mdi:solar-panel', 'scan': 'high', 'kind': 'value', 'unit': 'W', 'device_class': 'power', 'state_class': 'measurement', 'precision': 0},
        "third_party_pv_power": {'register': 10004, 'count': 2, 'vtype': 'S_DWORD', 'rtype': 'read', 'icon': 'mdi:solar-power-variant', 'scan': 'high', 'kind': 'value', 'unit': 'W', 'device_class': 'power', 'state_class': 'measurement', 'precision': 0, 'category': 'diagnostic'},
        "battery_charging_power": {'register': 10008, 'count': 2, 'vtype': 'S_DWORD', 'rtype': 'read', 'icon': 'mdi:battery-arrow-up', 'scan': 'high', 'kind': 'value', 'unit': 'W', 'device_class': 'power', 'state_class': 'measurement', 'precision': 0, 'split': 'negative_only'},
        "battery_discharging_power": {'register': 10008, 'count': 2, 'vtype': 'S_DWORD', 'rtype': 'read', 'icon': 'mdi:battery-arrow-down', 'scan': 'high', 'kind': 'value', 'unit': 'W', 'device_class': 'power', 'state_class': 'measurement', 'precision': 0, 'split': 'positive_only'},
        "load_power": {'register': 10010, 'count': 2, 'vtype': 'S_DWORD', 'rtype': 'read', 'icon': 'mdi:home-lightning-bolt', 'scan': 'high', 'kind': 'value', 'unit': 'W', 'device_class': 'power', 'state_class': 'measurement', 'precision': 0},
        "grid_export_power": {'register': 10012, 'count': 2, 'vtype': 'S_DWORD', 'rtype': 'read', 'icon': 'mdi:transmission-tower-export', 'scan': 'high', 'kind': 'value', 'unit': 'W', 'device_class': 'power', 'state_class': 'measurement', 'precision': 0, 'split': 'negative_only'},
        "grid_import_power": {'register': 10012, 'count': 2, 'vtype': 'S_DWORD', 'rtype': 'read', 'icon': 'mdi:transmission-tower-import', 'scan': 'high', 'kind': 'value', 'unit': 'W', 'device_class': 'power', 'state_class': 'measurement', 'precision': 0, 'split': 'positive_only'},
        "battery_soc": {'register': 10014, 'count': 1, 'vtype': 'U_WORD', 'rtype': 'read', 'icon': 'mdi:battery', 'scan': 'high', 'kind': 'value', 'unit': '%', 'device_class': 'battery', 'state_class': 'measurement', 'precision': 0},
        "pv_total_generation": {'register': 10018, 'count': 2, 'vtype': 'U_DWORD', 'rtype': 'read', 'icon': 'mdi:counter', 'scan': 'low', 'kind': 'value', 'unit': 'kWh', 'device_class': 'energy', 'state_class': 'total_increasing', 'precision': 1, 'scale': 0.1},
        "max_charge_power": {'register': 10036, 'count': 2, 'vtype': 'S_DWORD', 'rtype': 'read', 'icon': 'mdi:battery-charging-high', 'scan': 'low', 'kind': 'value', 'unit': 'W', 'device_class': 'power', 'state_class': 'measurement', 'precision': 0, 'category': 'diagnostic'},
        "max_discharge_power": {'register': 10038, 'count': 2, 'vtype': 'S_DWORD', 'rtype': 'read', 'icon': 'mdi:battery-arrow-down-outline', 'scan': 'low', 'kind': 'value', 'unit': 'W', 'device_class': 'power', 'state_class': 'measurement', 'precision': 0, 'category': 'diagnostic'},
        "ac_grid_output_power": {'register': 10208, 'count': 2, 'vtype': 'S_DWORD', 'rtype': 'read', 'icon': 'mdi:flash', 'scan': 'high', 'kind': 'value', 'unit': 'W', 'device_class': 'power', 'state_class': 'measurement', 'precision': 0},
        "rated_energy": {'register': 10250, 'count': 2, 'vtype': 'U_DWORD', 'rtype': 'read', 'icon': 'mdi:battery', 'scan': 'low', 'kind': 'value', 'unit': 'kWh', 'device_class': 'energy', 'precision': 1, 'scale': 0.1},
        "cumulative_charge_energy": {'register': 10262, 'count': 2, 'vtype': 'U_DWORD', 'rtype': 'read', 'icon': 'mdi:battery-plus', 'scan': 'low', 'kind': 'value', 'unit': 'kWh', 'device_class': 'energy', 'state_class': 'total_increasing', 'precision': 1, 'scale': 0.1},
        "cumulative_discharge_energy": {'register': 10264, 'count': 2, 'vtype': 'U_DWORD', 'rtype': 'read', 'icon': 'mdi:battery-minus', 'scan': 'low', 'kind': 'value', 'unit': 'kWh', 'device_class': 'energy', 'state_class': 'total_increasing', 'precision': 1, 'scale': 0.1},
        "ems_mode_mask": {'register': 32774, 'count': 1, 'vtype': 'U_WORD', 'rtype': 'read', 'icon': 'mdi:format-list-checks', 'scan': 'low', 'kind': 'value', 'precision': 0, 'category': 'diagnostic'},
        "parallel_capability_mask": {'register': 32775, 'count': 1, 'vtype': 'U_WORD', 'rtype': 'read', 'icon': 'mdi:feature-search', 'scan': 'low', 'kind': 'value', 'precision': 0, 'category': 'diagnostic', 'own_range': True},
        "pv_power": {'icon': 'mdi:solar-panel', 'scan': 'high', 'kind': 'calc', 'unit': 'W', 'device_class': 'power', 'state_class': 'measurement', 'precision': 0, 'mode': 'sum', 'deps': {'pcs': {'register': 10002, 'count': 2, 'vtype': 'S_DWORD', 'rtype': 'read', 'scan': 'high'}, 'third_party_pv_power': {'register': 10004, 'count': 2, 'vtype': 'S_DWORD', 'rtype': 'read', 'scan': 'high'}}},
    },
    "text_sensor": {
        "battery_status": {'register': 10001, 'count': 1, 'vtype': 'U_WORD', 'rtype': 'read', 'icon': 'mdi:battery', 'scan': 'high', 'kind': 'states', 'states': {0: 'Idle', 1: 'Charging', 2: 'Discharging', 3: 'Sleep'}},
        "device_sn": {'register': 10100, 'count': 12, 'vtype': 'RAW', 'rtype': 'read', 'icon': 'mdi:identifier', 'scan': 'low', 'kind': 'char'},
        "product_name": {'register': 10100, 'count': 12, 'vtype': 'RAW', 'rtype': 'read', 'icon': 'mdi:information', 'scan': 'low', 'kind': 'product'},
        "device_sw_version": {'register': 10112, 'count': 6, 'vtype': 'RAW', 'rtype': 'read', 'icon': 'mdi:information', 'scan': 'low', 'kind': 'char'},
        "device_model": {'register': 32768, 'count': 5, 'vtype': 'RAW', 'rtype': 'read', 'icon': 'mdi:information', 'scan': 'low', 'kind': 'char'},
    },
    "binary_sensor": {
        "backup_soc_enable": {'register': 60003, 'count': 1, 'vtype': 'U_WORD', 'rtype': 'holding', 'icon': 'mdi:battery-lock', 'scan': 'low', 'kind': 'bool'},
        "modbus_connection": {'kind': 'connection', 'device_class': 'connectivity', 'category': 'diagnostic', 'icon': 'mdi:lan-connect'},
    },
    "number": {
        "battery_power_setpoint": {'register': 10071, 'count': 2, 'vtype': 'S_DWORD', 'rtype': 'holding', 'unit': 'W', 'icon': 'mdi:lightning-bolt', 'kind': 'power_setpoint', 'min': -10000, 'max': 10000, 'step': 1},
        "charging_limit_soc": {'register': 60000, 'count': 1, 'vtype': 'U_WORD', 'rtype': 'holding', 'unit': '%', 'icon': 'mdi:battery-arrow-up', 'kind': 'soc_limit', 'scan': 'low', 'min': 80, 'max': 100, 'step': 1, 'capability_bit': 0, 'needs_backup_enable': False},
        "discharge_limit_soc": {'register': 60001, 'count': 1, 'vtype': 'U_WORD', 'rtype': 'holding', 'unit': '%', 'icon': 'mdi:battery-arrow-down', 'kind': 'soc_limit', 'scan': 'low', 'min': 0, 'max': 20, 'step': 1, 'capability_bit': 1, 'needs_backup_enable': False},
        "backup_reserve_soc": {'register': 60002, 'count': 1, 'vtype': 'U_WORD', 'rtype': 'holding', 'unit': '%', 'icon': 'mdi:battery-lock', 'kind': 'soc_limit', 'scan': 'low', 'min': 0, 'max': 100, 'step': 1, 'capability_bit': 2, 'needs_backup_enable': True},
    },
    "select": {
        "operating_mode": {'register': 10064, 'count': 1, 'vtype': 'U_WORD', 'rtype': 'holding', 'icon': 'mdi:cog', 'scan': 'high', 'kind': 'mode', 'options': {'Self-Consumption Mode': 0, 'Time Of Use Mode': 1, 'Third-Party Controlled': 3, 'Custom Mode': 4, 'Socket Overlay Mode': 5, 'Smart Mode': 6, 'Dynamic Tariff Mode': 7}, 'option_bits': {0: 0, 1: 1, 3: 5, 4: 2, 5: 4, 6: 3, 7: 6}, 'hold': 15},
    },
}

REGISTERS = {model: _SOLARBANK for model in MODEL_NAMES}
